services:
  app:
    image: dudes-build
    command: sh -c "pnpm run db:migrate:deploy && node dist/apps/backend-api/main.js"
    container_name: dudes-app
    working_dir: /usr/src/dudes
    environment:
      - ADMIN_URL=${ADMIN_URL}
      - CLIENT_URL=${CLIENT_URL}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CALLBACK_URL=${TWITCH_CALLBACK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - VITE_CJS_IGNORE_WARNING=${VITE_CJS_IGNORE_WARNING}
      - VITE_CLIENT_SOCKET_HOST=${VITE_CLIENT_SOCKET_HOST}
    user: $DOCKER_USER

  website:
    image: dudes-build
    command: sh -c "cd apps/website && npx remix-serve build/index.js"
    environment:
      - PORT=${REMIX_PORT}
    container_name: dudes-website
    working_dir: /usr/src/dudes
    user: $DOCKER_USER

  postgres:
    image: postgres:15-alpine
    container_name: dudes-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dudes
      - POSTGRES_USER=dudes
      - POSTGRES_DB=dudes

  nginx:
    image: nginx:alpine
    container_name: dudes-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  postgres-data:

networks:
  default:
    external: true
    name: scoobydoo
